console.log(typeof []);
console.log(typeof {});
console.log(typeof '');
console.log(typeof 1);
console.log(typeof true);
console.log(typeof null);
console.log(typeof undefined);
// object
// object
// string
// number
// boolean
// object
// undefined
